// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SsiAnalyzer.Infrastructure.Persistence;

#nullable disable

namespace SsiAnalyzer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221094812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionStepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExpectedImpact")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeEstimate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.SsiSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BuildRelationships")
                        .HasColumnType("double precision");

                    b.Property<double>("EngageInsights")
                        .HasColumnType("double precision");

                    b.Property<double>("EstablishBrand")
                        .HasColumnType("double precision");

                    b.Property<double>("FindPeople")
                        .HasColumnType("double precision");

                    b.Property<double>("IndustryAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("IndustryRankPercentile")
                        .HasColumnType("integer");

                    b.Property<double>("NetworkAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("NetworkRankPercentile")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("SsiSnapshots");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.ActionItem", b =>
                {
                    b.HasOne("SsiAnalyzer.Domain.Entities.User", "User")
                        .WithMany("ActionItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("SsiAnalyzer.Domain.Entities.SsiSnapshot", "Snapshot")
                        .WithMany("Recommendations")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.SsiSnapshot", b =>
                {
                    b.HasOne("SsiAnalyzer.Domain.Entities.User", "User")
                        .WithMany("Snapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.SsiSnapshot", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("SsiAnalyzer.Domain.Entities.User", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
